services:
  vox-caster-bot:
    image: ghcr.io/atkrv/vox-caster-bot:latest
    container_name: vox-caster-bot
    restart: unless-stopped
    working_dir: /data
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./config.yaml:/config/config.yaml:ro
      - ./:/data
